regions:
  - global
  - us-east-1

blocklist:
- "999999999999"

resource-types:
  excludes:
  - IAMUser
  - IAMUserPolicyAttachment
  - IAMUserPolicy
  - IAMUserAccessKey
  - IAMGroup
  - IAMUserGroupAttachment
  - IAMGroupPolicyAttachment
  
  - ECRRepository
  - ECRRepositoryPolicy
  - ECRPublicRepository
  - ECRPublicRepositoryPolicy
 
bypass-alias-check-accounts:
  - "897279497116"

accounts:
  "897279497116": {} 
